language: java
script: mvn test -Dtest=TEST_CONFIG
after_script: ./post-test.bash
notifications:
     email:
         recipients:
             - dhutchis@mit.edu
         on_success: change
         on_failure: always
